### ISSUE TITLE
State source of APIs?

### ISSUE THREAD

**Issue by MikeRalphson** [SOM-Research/hapi#1]
Hi [APIs-guru OpenAPI-directory](https://github.com/apis-guru/openapi-directory) maintainer here.

I just thought it might be nice if you could acknowledge the source of the API definitions.

Saying they are **"generated with our tool APIDiscoverer"** is more than a little misleading when the API definitions appear to hail from APIs.guru and Mashape.

Organising the APIs by source would allow us to see where the API definitions come from, including any generated by your tool. It would also allow users of your repository to be able to find updated versions.

**Comment by MikeRalphson** [comment]
Many thanks - I think the updated README now shows both projects in a good light.

**Comment by hamzaed** [comment]
Dear Mike,

First I would like to congratulate you for the excellent job you're doing in APIs.guru. Regarding the issue, I should apologize for the misleading.  We were already in the process of organizing the sources. 

I'm glad that you're satisfied with the updated README. 

Best regards,
Hamza
